/
ALTER TABLE BODEGA DROP CONSTRAINT BODEGAPAIS_FK;
/
ALTER TABLE BODEGA DROP CONSTRAINT BODEGADUENO_FK1;
/
ALTER TABLE BOD_MARCA DROP CONSTRAINT BODMARCAMARCA_FK;
/
ALTER TABLE BOD_MARCA DROP CONSTRAINT BODMARCABODEGA_FK1;
/
ALTER TABLE CALENDARIO_EDICION DROP CONSTRAINT CALEDICCONCURSO_FK;
/
ALTER TABLE CATADOREXPERTO DROP CONSTRAINT CEXPERTO_FK;
/
ALTER TABLE CLASIFICACION_VINO DROP CONSTRAINT CVINONIVEL_FK;
/
ALTER TABLE CONC_ORGAN DROP CONSTRAINT CONCORGANORGAN_FK;
/
ALTER TABLE CONC_ORGAN DROP CONSTRAINT CONCORGANCONCURSO_FK;
/
ALTER TABLE COSECHA DROP CONSTRAINT COSECHABOD_FK1;
/
ALTER TABLE COSECHA DROP CONSTRAINT COSECHAUVAV_FK;
/
ALTER TABLE DENOM_ORIGEN DROP CONSTRAINT DENOMORIREG_FK1;
/
ALTER TABLE DENOM_ORIGEN DROP CONSTRAINT DENOMORIUVA_FK;
/
ALTER TABLE DO_BODEGA DROP CONSTRAINT DOBODBOD_FK1;
/
ALTER TABLE DO_BODEGA DROP CONSTRAINT DOBODDENO_FK1;
/
ALTER TABLE HIST_PRECIO DROP CONSTRAINT HISTPREPRESEN_FRK1;
/
ALTER TABLE JUEZ DROP CONSTRAINT JUEZCEXPERT_FK;
/
ALTER TABLE JUEZ DROP CONSTRAINT JUEZCALENEDIC_FK1;
/
ALTER TABLE MARCA DROP CONSTRAINT MARCACLASIFV_FK;
/
ALTER TABLE MUESTRA_BODEGA DROP CONSTRAINT MUEBODPART_FK;
/
ALTER TABLE MUESTRA_BODEGA DROP CONSTRAINT MUEBODMARCA_FK;
/
ALTER TABLE MUESTRA_CATADORES DROP CONSTRAINT MUECATMARCA_FK;
/
ALTER TABLE PARTICIPANTE DROP CONSTRAINT PARTCALENDE_FK1;
/
ALTER TABLE PARTICIPANTE DROP CONSTRAINT PARTCPRINC_FK;
/
ALTER TABLE PARTICIPANTE DROP CONSTRAINT PARTBODEG_FK2;
/
ALTER TABLE PRESENTACION DROP CONSTRAINT PRESENMARCA_FK;
/
ALTER TABLE REGION_PRODUCTORA DROP CONSTRAINT REGPRODPAIS_FK;
/
ALTER TABLE REGULA DROP CONSTRAINT REGULAPAIS_FK;
/
ALTER TABLE REGULA DROP CONSTRAINT REGULAORGANIZA_FK;
/
ALTER TABLE VALORACIONBODEGA DROP CONSTRAINT VALORBODMUESTRA_FK1;
/
ALTER TABLE VALORACIONBODEGA DROP CONSTRAINT VALORBODJUEZ_FK2;
/
ALTER TABLE VALORACIONPARTICIPANTE DROP CONSTRAINT VALORPARTMUESTRA_FK1;
/
ALTER TABLE VALORACIONPARTICIPANTE DROP CONSTRAINT VALORPARTPARTI_FK;
/
DROP TRIGGER valoracionp_secuencia ;
/
DROP SEQUENCE valoracionp_sqnc;
/
DROP TRIGGER valoracionb_secuencia;
/
DROP SEQUENCE valoracionb_sqnc;
/
DROP TRIGGER uvavariedad_secuencia;
/
DROP SEQUENCE uvavariedad_sqnc;
/
DROP TRIGGER region_secuencia;
/
DROP SEQUENCE region_sqnc;
/
DROP TRIGGER presentacion_secuencia;
/
DROP SEQUENCE presentacion_sqnc;
/
DROP TRIGGER participante_secuencia;
/
DROP SEQUENCE participante_sqnc;
/
DROP TRIGGER pais_secuencia;
/
DROP SEQUENCE pais_sqnc;
/
DROP TRIGGER organizacion_secuencia;
/
DROP SEQUENCE organizacion_sqnc;
/
DROP TRIGGER muestrab_secuencia;
/
DROP SEQUENCE muestrab_sqnc;
/
DROP TRIGGER marca_secuencia;
/
DROP SEQUENCE marca_sqnc;
/
DROP TRIGGER denom_origen_secuencia;
/
DROP SEQUENCE denom_origen_sqnc;
/
DROP TRIGGER cosecha_secuencia;
/
DROP SEQUENCE cosecha_sqnc;
/
DROP TRIGGER concurso_secuencia;
/
DROP SEQUENCE concurso_sqnc;
/
DROP TRIGGER cvino_secuencia;
/
DROP SEQUENCE cvino_sqnc;
/
DROP TRIGGER cprincipiante_secuencia;
/
DROP SEQUENCE cprincipiante_sqnc;
/
DROP TRIGGER cexperto_secuencia;
/
DROP SEQUENCE cexperto_sqnc;
/
DROP TRIGGER calendarioe_secuencia;
/
DROP SEQUENCE calendarioe_sqnc;
/
DROP TRIGGER bodega_secuencia;
/
DROP SEQUENCE bodega_sqnc;
/
DROP TABLE VALORACIONPARTICIPANTE;
/
DROP TABLE VALORACIONBODEGA;
/
DROP TABLE UVAVARIEDAD;
/
DROP TYPE NOMBRE_VA;
/
DROP TABLE REGULA;
/
DROP TABLE REGION_PRODUCTORA;
/
DROP TABLE PRESENTACION;
/
DROP TABLE PARTICIPANTE;
/
DROP TABLE PAIS;
/
DROP TABLE ORGANIZACION;
/
DROP TABLE MUESTRA_CATADORES;
/
DROP TABLE MUESTRA_BODEGA;
/
DROP TABLE MARCA;
/
DROP TYPE MARIDAJE_VA;
/
DROP TABLE JUEZ;
/
DROP TABLE HIST_PRECIO;
/
DROP TABLE DO_BODEGA;
/
DROP TABLE DENOM_ORIGEN;
/
DROP TABLE COSECHA;
/
DROP TABLE CONC_ORGAN;
/
DROP TABLE CONCURSO;
/
DROP TABLE CLASIFICACION_VINO;
/
DROP TYPE VOL_VA;
/
DROP TABLE CATADORPRINCIPIANTE;
/
DROP TABLE CATADOREXPERTO;
/
DROP TYPE PUBLICACION_VA;
/
DROP TABLE CALENDARIO_EDICION;
/
DROP TABLE BOD_MARCA;
/
DROP TABLE BODEGA;
/
DROP TYPE DATOS_C;
/
DROP TYPE UNIDADMONETARIA;
/
DROP TYPE CALIFICACION_NT;
/
DROP TYPE CALIFICACION;
/
DROP TYPE HECHO_NT;
/
DROP TYPE HECHO;
/
DROP TYPE LUGAR;
/
DROP TYPE PERSONAL_CONTACTO_VA;
/
DROP TYPE PERSONAL_CONTACTO;
/
DROP TYPE TELEFONO_VA;
/
DROP TYPE TELEFONO;
/
DROP TYPE ESCALAEVALUACION_NT;
/
DROP TYPE ESCALAEVALUACION;
/
DROP TYPE PREMIO_NT;
/
DROP TYPE PREMIO;
/
DROP TYPE EXPORTACION_NT;
/
DROP TYPE EXPORTACION;
/
DROP TYPE TIPO_VALOR_NT;
/
DROP TYPE TIPO_VALOR;
/
DROP TYPE COSTO_NT;
/
DROP TYPE COSTO;
/
DROP TYPE VALORACION_NT;
/
DROP TYPE VALORACION;
/


